### ISSUE TITLE
Depósitos de agua no cerrados

### ISSUE THREAD

**Issue by javiersanp** [AnderPijoan/cat2osm#11]
Hola
Se me ha dado el caso de depósitos de agua en los que en los que el área está dividida en varias líneas con las etiquetas landuse=reservoir en cada una de ellas. Al validar, Josm,  da 'La vía estilo área no ha sido cerrada'. Eso obliga a combinar varias vías en una (C) o poner las etiquetas en una relación multipolígono. Puede ser un fallo del programa al no crear una relación.

**Comment by cruzki** [comment]
La relación está creada y a mapnik le gusta, pero por alguna razón a JOSM no :(

De todas formas, con el agua y las subestaciones pasan cosas MUUUUUUUUY raras en catastro (tenemos un lago artificial localizado en ciudad real que es de risa).

**Comment by AnderPijoan** [comment]
Este fallo est documentado en la wiki. En catastro estos elementos que
est en el archivo de "Elementos Lineales" muchas veces vienen
representados con geometras independientes que no estn ni conectadas
entre si.

Cat2Osm al principio corta todas las geometras en en vas de dos nodos
para as reutilizar el mximo posible en geometras que se superpongan. Una
vez estn todas las geometras ledas, para conectar las vas comprueba
primero si pertenecen a la misma geometra y segundo si estn siendo usadas
por ms geometras porque en ese caso en vez de unirlo, tiene que crear una
relacin.

En el caso de los pozos que comentas, al ser dos trozos independientes,
aunque compartan un nodo no pertenecen a la misma geometra y entonces
Cat2Osm no los une.

El 2 de abril de 2012 21:31, javiersanp <
reply@reply.github.com

> escribi:
> 
> Hola
> Se me ha dado el caso de depsitos de agua en los que en los que el rea
> est dividida en varias lneas con las etiquetas landuse=reservoir en cada
> una de ellas. Al validar, Josm,  da 'La va estilo rea no ha sido
> cerrada'. Eso obliga a combinar varias vas en una (C) o poner las
> etiquetas en una relacin multipolgono. Puede ser un fallo del programa al
> no crear una relacin.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AnderPijoan/cat2osm/issues/11

## 

Ander Pijoan Lamas
Ingeniero Tcnico en Informtica de Gestin
Universidad de Deusto

Contacto:
Email: ander.pijoan@deusto.es
Mvil: +34 664471228

**Comment by javiersanp** [comment]
Ok. De todas formas es fácil de detectar y corregir.

Saludos.
