### ISSUE TITLE
Unir tramos de la misma calle

### ISSUE THREAD

**Issue by cdavila** [AnderPijoan/cat2osm#12]
En muchos casos una misma calle está dividida en múltiples trozos, algunos de ellos de muy poca longitud. Sería perfecto si el programa los uniera por nombre siempre que sea posible. En algunos casos no se podrá, porque físicamente no están conectados o lo están por un punto intermedio de una de las vías.

**Comment by AnderPijoan** [comment]
Hecho. Aún y así hay calles que no son únicamente una geometría si no que se parten en más "ramas" (como por ejemplo formando una Y, si la calle tiene una rotonda en medio...). En esos casos obviamente se dejan las ramas sueltas ya que no podrían formar una única vía. 

En definitiva se han simplificado las calles por nombre lo máximo posible.
