### ISSUE TITLE
Licencia software libre

### ISSUE THREAD

**Issue by sim6** [AnderPijoan/cat2osm#18]
Hola,

Primero, gracias por el trabajo realizado.

Ha pensado en licenciar esta herramienta bajo una licencia de software libre?

Gracias de nuevo
y hasta pronto.

**Comment by cruzki** [comment]
En principio la licencia será "as is" pero estoy intentando que ander ponga la licencia WTFPL: http://en.wikipedia.org/wiki/WTFPL.

**Comment by AnderPijoan** [comment]
Hecho.
