### ISSUE TITLE
Intentar mejorar la unión de los distintos tramos de una calle

### ISSUE THREAD

**Issue by cdavila** [AnderPijoan/cat2osm#21]
La versión 20-04-2012 une ejes que tienen el mismo nombre y es una mejora notable, pero al unir distintos tramos de una vía parece que le gusta más unir tramos que forman ángulo que los que siguen la línea recta:
A-------B--------C
             |
            D
En situaciones como la del esquema suele unir los tramos tipo ABD o DBC en vez de los de tipo ABC. No sé si se le podría "enseñar" a preferir las rectas.

**Comment by cdavila** [comment]
El esquema ha quedado alterado al subirlo porque ha quitado los espacios. El pundo D va debajo del B
A-------B--------C
//////////|//////////
E-------D

**Comment by cruzki** [comment]
Entonces debería de unir ABC y DE quedaría unido en otro tramo? Estoy va a haber que pensárselo con calma como hacemos "crecer las vías".

**Comment by cdavila** [comment]
Esto del ASCII art no es lo mío y no consigo representar claramente las cosas. A ver si en vertical...
A
|
B-D
|
C
Lo lógico es que uniera ABC en una vía y BD lo dejara en otra. Este ejemplo es demasiado simple y realmente daría un poco igual que cree ABC+BD o ABD+BC, pero cuando la vía está más ramificada sí es más importante cómo haga la unión. Creo que lo mejor es que cuando se me presente otro caso con datos reales creados por cat2osm te haga un osm sólo con esos datos y te lo mande.

**Comment by cruzki** [comment]
La verdad es que si, porque cuando las vías no tienen nombre, tampoco tengo yo muy claro cual es la forma más coherente de unirlas :S

**Comment by AnderPijoan** [comment]
Hecho
