### ISSUE TITLE
Opción para computar la envolvente de un edificio

### ISSUE THREAD

**Issue by cruzki** [AnderPijoan/cat2osm#23]
Usando geotool u otras librerías calcular las envolventes de los constru y eliminar los tags 3D. Es una pérdida de datos, pero puede gustar más en la lista de imports.

**Comment by AnderPijoan** [comment]
Lo que es necesario hacer es calcular la unión de los polígonos de la misma contru con:

polyUnion = (PolyDefault) polyUnion.union(p);

Hay que tener mucho ojo cuando no comparten una arista. En ese caso, son dos constru distintas.
