### ISSUE TITLE
Guardar los osm por masas / polígonos rústicos

### ISSUE THREAD

**Issue by cruzki** [AnderPijoan/cat2osm#24]
Una vez realizado la simplificación por masas/poligonos rusticos, guardar el .osm resultante en un fichero resultado. Esto trae varias ventajas:
- Facilita la edición en JOSM
- Facilita la subida a JOSM
- PERMITE GUARDAR RESULTADOS INTERMEDIOS!!!!!!!!!!

Obviamente, antes de ponerse a simplificar una masa habrá que comprobar si el fichero ya ha sido generado y poner una opción en el config que apunte a un fichero con una "máscara" de masas a procesar.

**Comment by AnderPijoan** [comment]
Hecho.
