### ISSUE TITLE
Eliminar relaciones, vías y nodos sin datos relevantes.

### ISSUE THREAD

**Issue by AnderPijoan** [AnderPijoan/cat2osm#6]

**Comment by javiersanp** [comment]
Hola
Por lo que he visto en el primer municipio que he convertido, había un centenar de líneas sin etiquetas y ningún nodo. Todas las líneas menos una tenían de 2 a 4 nodos y son elementos auxiliares de edificios (balcones, aleros del tejado, muros...) Todo ello son cosas que puede interesar revisar y etiquetar a mano. Yo pondría un fixme más que eliminar.
Un saludo, Javier Sánchez

**Comment by AnderPijoan** [comment]
De momento no hay traduccin para esos elementos y a veces con los datos de
catastro no queda claro si un balcn est en las 3 alturas de un edificio,
solo en el piso 3 u otras combinaciones y los renderizadores 3d todava no
estn preparados para ese tipo de elementos constructivos.

Adems en la lista de imports ha habido discusin con el alto nmero de
relaciones que todos estos "aadidos" a edificios suponan y que
OpenStreetMap no debera ser Catastro2 sino utilizar las cosas interesantes
para OpenStreetMap que Catastro pueda ofrecer. Con el edificio y su
referencia Catastral, puedes ir al portal de Catastro y comprobar esos
detalles adicionales.

De momento en vista de todo esto hemos optado por no sacarlo en el
resultado final pero cuando sea el momento es tan sencillo como cambiar un
false por un true en el cdigo de ShapeConstru en el mtodo de
ShapeValido() y aadir los tags que se hayan acordado.

Saludos.

El 2 de abril de 2012 21:27, javiersanp <
reply@reply.github.com

> escribi:
> 
> Hola
> Por lo que he visto en el primer municipio que he convertido, haba un
> centenar de lneas sin etiquetas y ningn nodo. Todas las lneas menos una
> tenan de 2 a 4 nodos y son elementos auxiliares de edificios (balcones,
> aleros del tejado, muros...) Todo ello son cosas que puede interesar
> revisar y etiquetar a mano. Yo pondra un fixme ms que eliminar.
> Un saludo, Javier Snchez
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AnderPijoan/cat2osm/issues/6#issuecomment-4886344

## 

Ander Pijoan Lamas
Ingeniero Tcnico en Informtica de Gestin
Universidad de Deusto

Contacto:
Email: ander.pijoan@deusto.es
Mvil: +34 664471228

**Comment by javiersanp** [comment]
Muro: barrier=wall. Alero de tejado: building=roof, layer=+1. Balcón... no se me ocurre. Sería necesitario revisarlo a mano.

**Comment by AnderPijoan** [comment]
La simplificación no termina de ir fina. Dependiendo de la población se deja vías sin simplificar y lo que es peor se come algunas necesarias.

**Comment by AnderPijoan** [comment]
Hecho.
