### ISSUE TITLE
Etiquetado de buildings dentro de parcela no acaba de ir fino

### ISSUE THREAD

**Issue by davefx** [AnderPijoan/cat2osm#9]
En uno de mis parches integrados, pretendí hacer que ciertas etiquetas relativas al uso del suelo en urbano sólo aparecieran en los buildings de una parcela (principalmente, las etiquetas "building=...").

Sin embargo, algo no termina de ir fino, ya que por ejemplo en el ayuntamiento de Puebla de Don Fadrique, tengo "building=yes" en lugar de "building=public"...

**Comment by AnderPijoan** [comment]
Con el arreglo de los usos y destinos de los registro 14 y 15 de Catastro (https://github.com/AnderPijoan/cat2osm/issues/8) ya sale como building=public.
